language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dohp.kim@gmail.com

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deplpy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/learn-Springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repository settings saved
    secret_access_key: $AWS_SECRET_KEY
    bucket: myspringboot-s3-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip is private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myspringboot-s3-build
    key: learn-Springboot.zip
    bundle_type: zip
    application: mySpringBoot
    deployment_group: mySpringBoot-group
    region: ap-northeast-2
    wait-until-deployed: true